### ISSUE TITLE
Use of longtable in \body causes formatting problems for long sections

### ISSUE THREAD

**Issue by markcoletti** [zachscrivena/simple-resume-cv#2]
When writing a CV that has a very long section, as can happen with bibliographies, that section is treated a as a single, monolithic entity for formatting purposes.  This means that long sections will be put on their own page, and any content longer than that page is lost.

See also [this](http://tex.stackexchange.com/questions/343563/biblatex-multi-bibliographies-forced-to-use-single-page-using-simple-resume-cv) stack exchange article.

**Comment by zachscrivena** [comment]
Thank you for your feedback! The use of the longtable package for layout is indeed causing the problem --- I've just released v3.0 that should work well because it uses a list for layout instead. Do let me know if there are further issues.
