### ISSUE TITLE
PAge break at a section

### ISSUE THREAD

**Issue by peyush** [zachscrivena/simple-resume-cv#3]
Hi there, I am facing an issue with the format. My section is doing a page break when the content becomes more than the space available on the page. Can't figure out where this happens in the preamble. Could you please help?

**Comment by zachscrivena** [comment]
Thank you for your feedback! Are you using the latest version of the template? I've made several recent changes to improve the compatibility of the template with other packages (e.g., biblatex). If you can share your code (or an example), I can help take a look.

**Comment by peyush** [comment]
Yes, sorry for the mistake. Was using the previous version. Now its working fine. Thanks

**Comment by zachscrivena** [comment]
Glad it works now =)
