### ISSUE TITLE
Paths for fonts

### ISSUE THREAD

**Issue by pierreganty** [zachscrivena/simple-resume-cv#6]
I have the Tinos fonts installed using TexLive 2017.
The [path](https://github.com/zachscrivena/simple-resume-cv/blob/d70720d32b7adca3e355f66f454e298e34527594/simpleresumecv.cls#L143) specified where to find these fonts triggers an error because the fonts are located elsewhere.
Removing Path=... from that [line](https://github.com/zachscrivena/simple-resume-cv/blob/d70720d32b7adca3e355f66f454e298e34527594/simpleresumecv.cls#L143) solves my problem.

**Comment by zachscrivena** [comment]
Thank you for the tip!
